spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: cars
    password: aaa
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: debug